INSERT INTO CATEGORY (name) VALUES ('Arts');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Architecture', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Business of Art', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Conservation, Restoration & Care', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Contemporary Art', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dance', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Digital Music', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fashion, Decorative Arts & Design', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Film', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Graphic Arts', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('History & Criticism', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Museums & Collections', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Music', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Painting', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Performing Arts', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Photography', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sculpture', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Study & Teaching', 1);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Techniques', 1);
INSERT INTO CATEGORY (name) VALUES ('Astronomy');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Astronomers & Astrophysicists - Biography', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Astronomical Star Guides', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Astrophysics & Space Science', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cosmology', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Galaxies - Astronomical Studies & Observations', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('History of Astronomy', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Outer Space - Observation & Exploration', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Stars - Astronomical Studies & Observations', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('The Solar System - Astronomical Studies & Observations', 2);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('The Universe - Astonomical Studies & Observations', 2);
INSERT INTO CATEGORY (name) VALUES ('Biography & Autobiography');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Artists, Architects & Photographers', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Business & Finance', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Education Biography', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Entertainment Biography', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Essays, Journals & Letters', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Film, Television & Music', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('General & Miscellaneous Biography', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Historical', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Holocaust', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Literary Biography', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Medical, Legal & Social Sciences', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Novelists, Poets & Playwrights', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Peoples & Cultures - Biography', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Political', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Reference', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religious', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Science, Mathematics & Technology', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Social & Health Issues', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sports & Adventure Biography', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Theatre & Performance Art', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Tragic Life Stories', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('True Crime', 3);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('War & Espionage', 3);
INSERT INTO CATEGORY (name) VALUES ('Biology and other natural sciences');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Biology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Biophysics', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Biostatistics', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Biotechnology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cytology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ecology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Genetics', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('History of Biology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Human Biology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Microbiology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Molecular', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Paleontology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Plants: Agriculture and Forestry', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Plants: Botany', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Virology', 4);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Zoology', 4);
INSERT INTO CATEGORY (name) VALUES ('Business & Economics');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Accounting', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('E-Commerce', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Econometrics', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Economics', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Human Resources', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Industries', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Investing', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Job Hunting & Careers', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Logistics', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Management & Leadership', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Markets', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mathematical Economics', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Personal Finance', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Popular', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Professional Finance', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Project Management', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Real Estate', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Responsibility and Business Ethics', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sales & Marketing', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Small Business', 5);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Trading', 5);
INSERT INTO CATEGORY (name) VALUES ('Chemistry');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Analytical Chemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Biochemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Chemistry - General & Miscellaneous', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('History of Chemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Inorganic Chemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Microchemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Organic Chemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Physical Chemistry', 6);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Technical & Industrial Chemistry', 6);
INSERT INTO CATEGORY (name) VALUES ('Children''s Books');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Activities, Crafts & Games', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Animals', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Arts, Music & Photography', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cars, Trains & Things That Go', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Comics & Graphic Novels', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computers & Technology', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Early Learning', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Education & Reference', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fairy Tales, Folk Tales & Myths', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geography & Cultures', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Growing Up & Facts of Life', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('History', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Holidays & Celebrations', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Humour', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Literature & Fiction', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mysteries & Detective Stories', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religions', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Science Fiction & Fantasy', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Science, Nature & How It Works', 7);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sports & Outdoors', 7);
INSERT INTO CATEGORY (name) VALUES ('Comics & Graphic Novels');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Alternative & Underground Comics', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Anime & Manga', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cartooning', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Children''s', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Comic Books - History & Criticism', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Comics & Graphic Novels - General & Miscellaneous', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('DC Comics & Graphic Novels', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Marvel Comics & Graphic Novels', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mystery & Thriller Comics & Graphic Novels', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Science Fiction, Fantasy & Horror Comics & Graphic Novels', 8);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Superhero Comics & Graphic Novels', 8);
INSERT INTO CATEGORY (name) VALUES ('Computers');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Algorithms and Data Structures', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Applications & Software', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Artificial Intelligence (AI)', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computer Business & Culture', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computer Certification & Training', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computer Graphics & Design', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computer Science', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computers - General & Miscellaneous', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cryptography', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cybernetics', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Databases', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Digital Photography', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Digital Video', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Enterprise Computing Systems', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hardware', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Home Computer User & Beginner', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Information Systems', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Internet & World Wide Web', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Lectures, monographs', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mac OS', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Media', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Microsoft Windows', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Networking', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('New to Computing', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Operating Systems', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Organization and Data Processing', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('PC & Video Games', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Professionals', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Programming', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Security', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('UNIX & Linux', 9);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Web Development', 9);
INSERT INTO CATEGORY (name) VALUES ('Cookbooks, Food & Wine');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Asian', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Baking & Desserts', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Barbecue & Grilling', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Beginner''s cookbook', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('French', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('International', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Italian', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Quick & Easy Meals', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Special Diet', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Vegetarian & Vegan', 10);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Wine & Beverages', 10);
INSERT INTO CATEGORY (name) VALUES ('Crime, Thrillers & Mystery');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Action & Adventure', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Anthologies', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cozy Mysteries & Amateur Sleuths', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Detective & Crime Fiction', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Historical', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Legal', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Medical', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military Thrillers', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Mystery Categories', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Thrillers Categories', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Police Stories', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Political', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychological', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Series', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Short Stories', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Spy Stories', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Technothrillers', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Thrillers', 11);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('True Crime', 11);
INSERT INTO CATEGORY (name) VALUES ('Earth Sciences');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cartography', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Earth History', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geochemistry', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geodesy', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geography', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geology', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geophysics', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hydrogeology', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Meteorology, Climatology', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mineralogy', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mining', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Oceanography', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Palaeontology', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Reference', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Rivers & Lakes', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('The Environment', 12);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Volcanoes, Earthquakes & Tectonics', 12);
INSERT INTO CATEGORY (name) VALUES ('Education Studies & Teaching');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Academic Administration', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Adult & Continuing Education', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Bilingual & Multicultural Education', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Education - General & Miscellaneous', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Education Management & Organisation', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Educational Guidance & Counseling', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Educational Theory, Research & History', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Elementary', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Higher & Further Education', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('History of Education', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Homeschooling', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Individual Colleges & Universities', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('International Conferences and Symposiums', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Philosophy of Education', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pre-school & Early Learning', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('School Education & Teaching', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Special Education', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Studying & Test Preparation', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Teaching & Teacher Training', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Teaching - Reading & Language', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Theses abstracts', 13);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Vocational', 13);
INSERT INTO CATEGORY (name) VALUES ('Engineering');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Aerospace Engineering', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Automotive', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Bioengineering', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Chemical Engineering', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Civil & Structural Engineering', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computer Technology', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Construction & Building Trades', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electrical & Electronic Engineering', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Energy & Power Resources', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Engineering - General & Miscellaneous', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Engineering Technology', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Environmental', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hydraulic Engineering', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Industrial Engineering & Materials Science', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanical Engineering & Dynamics', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Robotics & Artificial Intelligence', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Social & Cultural Aspects of Technology', 14);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Telecommunications', 14);
INSERT INTO CATEGORY (name) VALUES ('Erotica');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Arts & Photography', 15);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Comics & Manga', 15);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fiction', 15);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('LGBTQ+', 15);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Love, Erotic', 15);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 15);
INSERT INTO CATEGORY (name) VALUES ('Fantasy');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dark Fantasy', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fairy Tales', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('High Fantasy', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Low Fantasy', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Magical Realism', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Fantasy Fiction Categories', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Role-Playing Game Fiction', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Superhero Fiction', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sword And Sorcery', 16);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Urban Fantasy', 16);
INSERT INTO CATEGORY (name) VALUES ('Fiction');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Adventure Stories & Action', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('American Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Anthologies', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Classics', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Contemporary Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Drama', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Essays', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Family Sagas', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fantasy', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Historical', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Horror', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Humour', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Literary Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Metaphysical & Visionary', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Myths & Folklore', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Nautical & Maritime Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Peoples & Cultures - Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychological', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religious & Inspirational', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Short Stories', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('War & Military Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Westerns', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Women''s Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('World Fiction', 17);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Young Adult', 17);
INSERT INTO CATEGORY (name) VALUES ('History');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('African History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('American Studies', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ancient History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Archaeology', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Asian History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Australian & Oceanian History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Canadian History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Chinese History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('European History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Indian History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Islamic History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Latin American History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Middle Ages', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Middle Eastern History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Russian & Soviet History', 18);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('World History', 18);
INSERT INTO CATEGORY (name) VALUES ('Housekeeping & Leisure');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Activity & Game Books', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Antiques & Collectables', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Drawing', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fashion, Jewelry', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Floral & Nature Crafts', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Games: Board Games', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Games: Chess', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Gardening', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Glass & Metal Work', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Handicraft', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Handicraft: Cutting and Sewing', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Interior Design & Decoration', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Modelmaking', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Papercrafts', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Role-Playing & Fantasy Games', 19);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Woodworking & Carving', 19);
INSERT INTO CATEGORY (name) VALUES ('Jurisprudence & Law');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Business, Commercial & Financial Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Civil Rights Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Constitutional Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Courts & Trial Practice', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Criminal Law & Procedure', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Criminology, Forensic Science', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Criminology: Court. Examination', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Environmental Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Family Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Foreign & International Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('General & Miscellaneous Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Intellectual Property', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Labor Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Legal Reference', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Legal Theory & Philosophy', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Medical Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Real Estate & Property Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religious Law', 20);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Tort & Liability Law', 20);
INSERT INTO CATEGORY (name) VALUES ('Languages');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Arabic Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Chinese Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Comparative Studies', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dictionaries', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('English as a Foreign Language & Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('French Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('General & Miscellaneous Languages - Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('German Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Germanic Languages Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Grammar, dictionaries & phrasebooks', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hindi Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Indic Languages Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Indonesian Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Italian Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Japanese Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Korean Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Latin Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Polyglot Dictionaries', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Portuguese Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Rhetoric', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Romance Languages Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Russian Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Slavic Languages Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Spanish Language Reference', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Traditional Chinese Language Ref.', 21);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Turkish Language Reference', 21);
INSERT INTO CATEGORY (name) VALUES ('Linguistics');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Historical & Comparative Linguistics', 22);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Linguistics', 22);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Semiotics', 22);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sociolinguistics', 22);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Stylistics', 22);
INSERT INTO CATEGORY (name) VALUES ('Mathematics');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Algebra', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Analysis', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Applied Mathematics', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Automatic Control Theory', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Combinatorics', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computational Mathematics', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Computer Algebra', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Continued fractions', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Differential Equations', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Discrete Mathematics', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dynamical Systems', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Elementary', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Functional Analysis', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fuzzy Logic and Applications', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Game Theory', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Geometry and Topology', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Graph Theory', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Lectures', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Logic', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mathematical Foundations', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mathematical Physics', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mathematical Statistics', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mathematical Theory', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Number Theory', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Numerical Analysis', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Operator Theory', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Optimal control', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Optimization. Operations Research', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Probability', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Puzzle', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Symmetry and group', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('The complex variable', 23);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Wavelets and signal processing', 23);
INSERT INTO CATEGORY (name) VALUES ('Medicine');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Anatomy and physiology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Anesthesiology and Intensive Care', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cardiology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Chinese Medicine', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Clinical Medicine', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dentistry, Orthodontics', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dermatology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Diabetes', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Diseases', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Endocrinology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('ENT', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Epidemiology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Feng Shui', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Health-Related Professions', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Histology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Homeopathy', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Immunology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Infectious diseases', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Internal Medicine', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Medicine & Nursing Reference', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Medicine & Nursing Test Prep', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Molecular Medicine', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Natural Medicine', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Neurology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Neuroscience', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Nursing', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Oncology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ophthalmology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pediatrics', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pharmacology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Popular scientific literature', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychiatry', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Radiology', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Surgery, Orthopedics', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Therapy, Psychotherapy', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Trial', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Veterinary Medicine', 24);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Yoga, Ayurveda', 24);
INSERT INTO CATEGORY (name) VALUES ('Nature, Animals & Pets');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Animal Care & Pets', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Animals', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Birds', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cats', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dinosaurs', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dogs', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Exotic & Other Pets', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Field Guides', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fossils', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Home Aquarium', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Horses', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Insects & Arachnids', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mammals', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Marine & Aquatic Life', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Natural Disasters', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Natural History', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Natural Terrain', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Nature - Other', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Birds', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Birds', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Fish', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Memoirs', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Mice, Rabbits, Hamsters, Etc.', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Pigs', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pet Reptiles & Amphibians', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pets - General & Miscellaneous', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Plants & Fungi', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Stargazing - Amateur''s Manuals', 25);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Weather', 25);
INSERT INTO CATEGORY (name) VALUES ('Others');
INSERT INTO CATEGORY (name) VALUES ('Physics');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Astronomy: Astrophysics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Atomic & Molecular', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Chaos & Dynamic Systems', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Crystal Physics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electricity and Magnetism', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electrodynamics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('General Courses', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Light, Optics & Laser', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics: Fluid Mechanics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics: Mechanics of deformable bodies', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics: Nonlinear dynamics and chaos', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics: Oscillations and Waves', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics: Strength of Materials', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Mechanics: Theory of Elasticity', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Nuclear', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Optics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Physics of the Atmosphere', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Plasma Physics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Quantum Mechanics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Quantum Physics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Relativity', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Solid State Physics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Spectroscopy', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('States of Matter', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Theoretical Physics', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Theory of Relativity and Gravitation', 27);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Thermodynamics', 27);
INSERT INTO CATEGORY (name) VALUES ('Poetry');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('American Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ancient & Classical Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Arabic & Middle Eastern Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Asian Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Australian, New Zealand, & Pacific Island Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Canadian Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('English, Irish, & Scottish Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('European Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('General & Miscellaneous Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Inspirational & Religious Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Latin American & Caribbean Poetry', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Poetry Anthologies', 28);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Russian Poetry', 28);
INSERT INTO CATEGORY (name) VALUES ('Psychology');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Clinical Psychology', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cognitive Psychology', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Developmental Psychology', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Neuropsychology', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pedagogy', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychological Disorders', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychology - Theory, History & Research', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychopathy', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychotherapy', 29);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Social Psychology', 29);
INSERT INTO CATEGORY (name) VALUES ('Reference');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Almanacs & Yearbooks', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Atlases & Maps', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Consumer Guides', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Encyclopaedias', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Genealogy & Family History', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Library & Information Science', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Reference By Subject', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('School Guides & Test Preparation', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Thesauri', 30);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Writing', 30);
INSERT INTO CATEGORY (name) VALUES ('Religion & Spirituality');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Atheism & Agnosticism', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Bible', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Buddhism', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Christianity', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Esoteric, Occult, & Divination', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hinduism', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Islam', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Judaism', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Kabbalah', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Religions', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religious Conflict', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religious Studies', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sacred Texts', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Spirituality', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Taoism & Confucianism', 31);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Theosophy & New Age', 31);
INSERT INTO CATEGORY (name) VALUES ('Romance');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Collections & Anthologies', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Contemporary Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dark Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Erotic Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fantasy', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Gothic Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Historical Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Interracial', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('LGBTQ+ Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Romance Categories', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Paranormal Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Religious Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Romantic Comedy', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Romantic Westerns', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Science Fiction Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Time Travel Romance', 32);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Young Adult Romance', 32);
INSERT INTO CATEGORY (name) VALUES ('Science (General)');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('International Conferences and Symposiums', 33);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Research & Development', 33);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Science of Science', 33);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Scientific and popular: Journalism', 33);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Scientific-popular', 33);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Theories of Science', 33);
INSERT INTO CATEGORY (name) VALUES ('Science Fiction');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Alternate Realities', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cyberpunk', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dystopian Fiction', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fantasy Fiction', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('High Tech & Hard Sci-Fi', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military Science Fiction', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Sci-Fi', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Space Opera', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Space Western', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Steampunk', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Supernatural Fiction', 34);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Utopian Fiction', 34);
INSERT INTO CATEGORY (name) VALUES ('Self-Help, Relationships & Lifestyle');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Addiction & Recovery', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Aging', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Alternative Medicine & Natural Healing', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Beauty & Fashion', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Dating', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Diet & Nutrition', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Digital Lifestyle', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Divorce', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Emotional Healing', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Exercise & Fitness', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Families & Parents', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Health - Diseases & Disorders', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Love & Romance', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Marriage', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Men''s Health & Lifestyle', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Personal Growth & Inspiration', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pregnancy & Childcare', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Psychological Self-Help', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Relationships', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sexuality', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('The Art of Communication', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Weddings', 35);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Women''s Health & Lifestyle', 35);
INSERT INTO CATEGORY (name) VALUES ('Society, Politics & Philosophy');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ancient & Medieval Philosophy', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Anthropology', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Asian Philosophy', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Cultural', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ethnography', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('European & American Philosophy', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('General & Miscellaneous Philosophy', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Government & Politics', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('International Relations', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Journalism, Media', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Major Branches of Philosophical Study', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Philosophical Positions & Movements', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Politics', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Renaissance & Modern Philosophy', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Social Sciences', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Sociology', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Warfare & Defence', 36);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Women''s Studies', 36);
INSERT INTO CATEGORY (name) VALUES ('Sports, Hobbies & Games');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Air Sports', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Athletics & Gymnastics', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Ball Games', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Bike', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Boating & Sailing', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Bodybuilding', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Climbing & Mountaineering', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fencing', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Football & Rugby', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Golf', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hockey', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Hunting & Fishing', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Martial Arts', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Motor Sports', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Olympics & Olympic Sports', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Other Sports', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Outdoor & Adventure Sports', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Survival', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Training & Coaching', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Water Sports', 37);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Winter Sports', 37);
INSERT INTO CATEGORY (name) VALUES ('Technique');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Aerospace Equipment', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Automation', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Communication', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Construction', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Construction: Cement Industry', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Construction: Renovation and interior design', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Construction: Ventilation and Air Conditioning', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Fiber Optics', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Hardware', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Home Electronics', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Microprocessor Technology', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Radio', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Robotics', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Signal Processing', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: Telecommunications', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: TV. Video', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Electronics: VLSI', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Energy', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Energy: Renewable Energy', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Experiments, Instruments & Measurements', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Food Manufacturing', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Fuel Technology', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Heat', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Industrial Equipment and Technology', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Light Industry', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Marine & Nautical', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Materials', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Metallurgy', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Metrology', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military equipment', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military equipment: Missiles', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Military equipment: Weapon', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Nanotechnology', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Oil and Gas Technologies', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Others', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Patent Business. Ingenuity. Innovation', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Publishing', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Refrigeration', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Regulatory Literature', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Safety and Security', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Transport', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Transportation: Aviation', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Transportation: Cars, Motorcycles', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Transportation: Rail', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Transportation: Ships', 38);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Water Treatment', 38);
INSERT INTO CATEGORY (name) VALUES ('Travel');
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Africa - Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Asia - Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Atlases & Maps', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Australia & Oceania - Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Canadian & North American Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Europe - Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Food, Lodging & Transportation', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Latin American & Caribbean Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Middle East - Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Pictorial', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Reference', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Specialty Travel', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel - Cities of the World', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel - General & Miscellaneous', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel - Interests, Activities & Accommodations', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel - Natural & Man-made Wonders of the World', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel Essays & Descriptions', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel Photography', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('Travel Writing', 39);
INSERT INTO SUBCATEGORY (name, id_category_father) VALUES ('United States of America - Travel', 39);
